- id: trivyinit
  name: trivyinit
  entry: aquasec/trivy:0.46.1 image --download-db-only --exit-code 1
  language: docker_image
  pass_filenames: false

- id: trivyfs
  name: trivyfs
  entry: aquasec/trivy:0.46.1 fs --exit-code 1
  language: docker_image
  pass_filenames: false

- id: trivyk8
  name: trivyk8
  entry: aquasec/trivy:0.46.1 k8 --exit-code 1
  language: docker_image
  pass_filenames: false